<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/domene/pensjon/prosesser/rekonverterUPTilUT/v1/Binding/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://nav.no/domene/pensjon/prosesser/rekonverterUPTilUT/v1/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:rekonverterUPTilUT="http://nav.no/domene/pensjon/prosesser/rekonverterUPTilUT/v1">
  <wsdl:import namespace="http://nav.no/domene/pensjon/prosesser/rekonverterUPTilUT/v1" location="../rekonverterUPTilUT.wsdl">
    </wsdl:import>
  <wsdl:binding name="RekonverterUPTilUTBinding" type="rekonverterUPTilUT:RekonverterUPTilUT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="rekonverterUPTilUT">
      <soap:operation soapAction="http://nav.no/domene/pensjon/prosesser/rekonverterUPTilUT/v1/RekonverterUPTilUT/rekonverterUPTilUTRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RekonverterUPTilUT">
    <wsdl:port name="RekonverterUPTilUTPort" binding="tns:RekonverterUPTilUTBinding">
      <soap:address location="http://localhost:9080/pensjon-microflow-rekonverterUPTilUTProxyWeb/sca/RekonverterUPTilUTWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
