<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2/Binding" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2/Binding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl_1="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2" location="behandleEtteroppgjorUT.wsdl">
    </wsdl:import>
  <wsdl:binding name="BehandleEtteroppgjorUT_v2Binding" type="wsdl_1:BehandleEtteroppgjorUT_v2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="avbrytAutomatiskBehandling">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2/BehandleEtteroppgjorUT_v2/avbrytAutomatiskBehandlingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="behandleEtteroppgjor">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2/BehandleEtteroppgjorUT_v2/behandleEtteroppgjorRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="behandleTilbakekreving">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2/BehandleEtteroppgjorUT_v2/behandleTilbakekrevingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/tjeneste/domene/pensjon/behandleEtteroppgjorUT/v2/BehandleEtteroppgjorUT_v2/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BehandleEtteroppgjorUT_v2">
    <wsdl:port name="BehandleEtteroppgjorUT_v2Port" binding="tns:BehandleEtteroppgjorUT_v2Binding">
      <soap:address location="http://localhost:9080/pensjon-microflow-behandleEtteroppgjorUTProxyWeb/sca/BehandleEtteroppgjorUT_v2WSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
