<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/domene/pensjon/tjenester/erUngUfor/v1/Binding/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://nav.no/domene/pensjon/tjenester/erUngUfor/v1/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:erUngUfor="http://nav.no/domene/pensjon/tjenester/erUngUfor/v1">
  <wsdl:import namespace="http://nav.no/domene/pensjon/tjenester/erUngUfor/v1" location="../erUngUfor.wsdl">
    </wsdl:import>
  <wsdl:binding name="ErUngUforBinding" type="erUngUfor:ErUngUfor">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="erUngUfor">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="personIkkeFunnet">
        <soap:fault name="personIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ErUngUfor">
    <wsdl:port name="ErUngUforPort" binding="tns:ErUngUforBinding">
      <soap:address location="http://localhost:9080/pensjon-tjeneste-erUngUfor_v1Web/sca/ErUngUforWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
