<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Binding" targetNamespace="http://no/nav/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/Binding/" xmlns:behandleEndretForventetArbeidsinntekt="http://nav.no/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://no/nav/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/Binding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="../behandleEndretForventetArbeidsinntekt.wsdl" namespace="http://nav.no/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/v2"/>
  <wsdl:binding name="BehandleEndretForventetArbeidsinntekt_v2Binding" type="behandleEndretForventetArbeidsinntekt:BehandleEndretForventetArbeidsinntekt_v2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="behandleEndretForventetArbeidsinntekt">
      <soap:operation soapAction="http://no/nav/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/Binding/behandleEndretForventetArbeidsinntekt/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="behandleEndretForventetArbeidsinntektOgSendResultat">
      <soap:operation soapAction="http://no/nav/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/Binding/behandleEndretForventetArbeidsinntektOgSendResultat/"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BehandleEndretForventetArbeidsinntekt_v2">
    <wsdl:port binding="tns:BehandleEndretForventetArbeidsinntekt_v2Binding" name="BehandleEndretForventetArbeidsinntekt_v2Port">
      <soap:address location="http://no/nav/domene/pensjon/prosesser/behandleEndretForventetArbeidsinntekt/Binding/BehandleEndretForventetArbeidsinntekt_v2/BehandleEndretForventetArbeidsinntekt_v2Port"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>