name: Release (Github Package Registry)

on:
  push:
    branches:
    - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Maven release
        run: ./releaseGithub.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
